common: &common
  adapter: postgresql
  username: dhamodaran
  password: dhamodaran
  encoding: UTF8
  host: 127.0.0.1
production:
  database: coepic
  host: 127.0.0.1
  <<: *common
development:
  database: coepic_dev
  <<: *common
test:
  database: coepic_test
  <<: *common

